spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id : STORAGE
          uri: lb://STORAGE
          predicates:
            - Query=name
        - id : myroute
          uri : http://httpbin.org/
          predicates:
            - Path=/get
            - Query=age
      discovery:
        locator:
          enabled: true
server:
  port: 5000
eureka:
  client:
    service-url:
      default-Zone: http://localhost:1111/eureka
logging:
  level:
    org.springframework.cloud.gateway: debug
